### ISSUE TITLE
where to download

### ISSUE THREAD

**Issue by MichaelPCgamer** [btbd/mtas#1]
I'm relatively new to Github and I'm really interested in testing this application but I can't find an executable file.  Do I have to run the code through a C++ IDE? README says "download latest version".

**Comment by MichaelPCgamer** [comment]
Ok I reached the bottom where it says "contribute" and I think Ik what to do now.

**Comment by btbd** [comment]
It's still a work-in-progress so you will have to download the source and build it yourself if you want to try it.
